### ISSUE TITLE
Standardize user roles

### ISSUE THREAD

**Issue by jeremi** [OpenSPP/openspp-base#2]
## Introduction

This specification outlines the requirements for creating and managing User Roles in OpenSPP, an Odoo-based system, leveraging OCA base_user_role. The goal is to manage access rights effectively and efficiently across the system.

### User Roles

User roles are divided into two main categories: Local and Global. Each role will have specific access rights.

**Local Roles**:

1. **Registrar**: This role is allowed to capture data related to their assigned area but doesn't have access to any other information.
2. **Support**: This role is allowed to view and respond to support requests only from their assigned area.

**Global Roles**:

1. **Admin**: This role has universal access and permissions to all system data and features.
2. **Finance**: This role has access to financial data across all areas.
3. **Program Manager**: This role has access to all area-specific data to allow for effective program coordination and management.
4. **Registrar**: This role has access to data capture features across all areas.
5. **Support**: This role can view and respond to all support requests.
6. **Support Manager**: This role can supervise and manage all support requests and activities across all areas.

### Area Assignment Management

For local roles, a User Interface (UI) is required to assign, modify, or remove the specific area to which a user has access.

## Role and Access Removal

If a role is unassigned from a user, all the permissions associated with that role are removed from the user's capabilities. Similarly, if an area is unassigned from a local role, the user with that role will not have access to any area-specific data.

## How to Use:

**1. Assign existing users to roles:**
- Go to Settings->Users and Computers->Roles.
- Open a role from the list.
- Open the "Users" tab.
- Click "Add a line" then search for the user to be added.
- The "Center Area" column can only be entered if the "Role Type" is "Local". When a center area is selected here, the user will be able to access records with the same center area.
- Click the "Save" button.

**2. Assign roles to users:**
- Go to Settings->Users and Computers->Users
- Select or create a new user.
- In the "Roles" tab add the roles that will be assigned to the user.
- The "Center Area" column can only be entered if the "Role Type" is "Local". When a center area is selected here, the user will be able to access records with the same center area.
- Click the "Save" button.

**Comment by gonzalesedwin1123** [comment]
Started working on this today.

**Comment by gonzalesedwin1123** [comment]
@jeremi I think I need to create our version of this module due to possible license issue of OCA server-backend (AGPL 3.0).

**Comment by adriancris** [comment]
hi @gonzalesedwin1123 
I have here a local registrar with assigned central area 6001 - Test Area 2 
This local registrar can see and select the other areas NOT assigned to it.
Please see screenshot. Thank you.
![Standardize user roles_Bug 1](https://github.com/OpenSPP/openspp-base/assets/138551361/cccd7563-bc64-4a5f-8c77-b516ecf9a3a6)

**Comment by adriancris** [comment]
hi @gonzalesedwin1123 
we still dont have modules for support users and program management roles. this is to test the access of each roles.

**Comment by adriancris** [comment]
As per @gonzalesedwin1123 , Discuss, Calendar, and Link tracker menu options are default Odoo modules, we can hide their menu until we find a need for them. Documents is the DMS module that we are using for the Change Request module. We can uninstall this because we are not using Change Request in ACF.

**Comment by adriancris** [comment]
@gonzalesedwin1123 
after removing a role from a user, nothing is automatically selected in user type thus when that user logs back in, error message appears. 
![image](https://github.com/OpenSPP/openspp-base/assets/138551361/f87f9379-41f7-47ad-ab3f-97c2d6de567d)

![image](https://github.com/OpenSPP/openspp-base/assets/138551361/50325f63-0334-40ac-a258-5fa8a4015779)

**Comment by gonzalesedwin1123** [comment]
Add the following to the global registrar and global program roles:

- OpenAPI User

**Comment by anthonymarkQA** [comment]
ODOO 17
ACF DEV
Findings: Returned to DEV

Local and global roles should be visible and can be used to assign to a user - pass

Local and global roles should be able to grant access respectively to the user associated with - fail
![image](https://github.com/user-attachments/assets/28a8be76-1cd4-4b79-87f3-7caf058cef18)

"From - To" dates should dictate the duration of access granted to the user - fail, can still login even after end date has passed.
![image](https://github.com/user-attachments/assets/65ccf139-4635-4371-a7d4-22924b0a09c1)

Defining the center area should let user have access on records associated with the center area - fail, cannot access any record
