### ISSUE TITLE
PMT Module Development

### ISSUE THREAD

**Issue by dasunhegoda** [OpenSPP/openspp-base#34]
Code developed up to now: [spp_pmt.zip](https://github.com/OpenSPP/openspp-api/files/13224371/spp_pmt.zip)

Actual use-case to understand the requirement: [Gazette 2128-24_E.pdf](https://github.com/OpenSPP/openspp-api/files/13224360/Gazette.2128-24_E.pdf)

The Proxy Means Testing (PMT) Module needs additional functionalities to enhance flexibility and user interaction. The proposed features are:

- User-Defined Indicators: Enable users to specify indicators through the UI, rather than having them hard-coded.
- Indicator Weights via UI: Allow users to set weights for each indicator via the UI.
- Automated Area Data for Household: Derive the 'Area' attribute of a Household from the pre-defined 'Areas'.

Acceptance Criteria:

- Users can input, edit, or delete indicators for PMT directly through the UI.
- Weights for each indicator can be set via the UI.
- The 'Area' field for Households is automatically populated based on existing 'Areas' data.

Note that improvements can be done based on the existing development. Refer to the attachment for details.

**Comment by adriancris** [comment]
@emjay0921 to hide the delete button in the custom field UI

**Comment by adriancris** [comment]
@gonzalesedwin1123 / @emjay0921 improvement: default weight and area-specific weight should NOT accept negative values

**Comment by adriancris** [comment]
QA Passed
Working as expected
Test cases executed:
TSOS-189
TSOS-190
TSOS-191

**Comment by adriancris** [comment]
tested and approved but actions were needed
