### ISSUE TITLE
Define a base project that install the minimum OpenSPP modules

### ISSUE THREAD

**Issue by jeremi** [OpenSPP/openspp-base#6]
How to use:
- Install the openspp_base module (Installing this will install all other OpenSPP modules

This needs to be installed as the base module when installing OpenSPP. This will have common modules which are common for all projects/products. 

Created a new module named spp_base which depends on;

"base",
"spp_area",
"spp_change_request",
"spp_event_data",
"spp_idpass",
"spp_idqueue",
"spp_service_points",
"spp_custom_field",
"spp_custom_fields_ui",
"spp_programs",

**Comment by gonzalesedwin1123** [comment]
Any update for this ticket @emjay0921?

**Comment by emjay0921** [comment]
Created a new module named `spp_base` which depends on;

"base",
"spp_area",
"spp_change_request",
"spp_event_data",
"spp_idpass",
"spp_idqueue",
"spp_service_points",
"spp_custom_field",
"spp_custom_fields_ui",
"spp_programs",

If anymore modules needed to be installed, please comment on this.

**Comment by gonzalesedwin1123** [comment]
@emjay0921 The OpenG2P modules are also needed here

**Comment by emjay0921** [comment]
Done @gonzalesedwin1123
